import { Component, OnInit } from '@angular/core';
import * as Highcharts from 'highcharts';
import { interval } from 'rxjs';
import { take } from 'rxjs/operators';
import { CaremonitorService } from './caremonitor.service';
import {
  IStateVaccinationMetrics,
  Istatistics,
} from './types/api.response.type';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent implements OnInit {
  title = 'caremonitor';
  Highcharts: typeof Highcharts = Highcharts;
  chartOptions: Highcharts.Options;
  statsData: any;

  newCases: number;
  InterStateCases: number;
  hospitalCases: number;
  icuCases: number;
  ventilatorCases: number;

  Test_24hrs: number;
  NewCases: number;
  Tested: number;
  LocalCases: number;
  Deaths: number;
  Cases: number;

  nswHealthDosesDaily: number;
  nswHealthDosesCumulative: number;
  gpNetworkDosesCumulative: number;
  allProvidersDosesCumulative: number;
  totalData: any;
  locationsData: any;
  data: any[] = [];
  constructor(private caremonitorService: CaremonitorService) {}

  ngOnInit(): void {
    this.getColumnData();
    this.getStats();
    this.getVaccinationStats();
  }


  getColumnData(): void {
    this.caremonitorService.getCaseLocationsData().subscribe(
      (res: any) => {
        this.data = [];
        this.locationsData = res;
        this.getLocationsData(this.locationsData);
      },
      (err) => {
        this.data = [];
        this.locationsData = {
          data: [
            { notification_date: '22-Jan', Cases: 0 },
            { notification_date: '23-Jan', Cases: 0 },
            { notification_date: '24-Jan', Cases: 0 },
            { notification_date: '25-Jan', Cases: 3 },
            { notification_date: '26-Jan', Cases: 0 },
            { notification_date: '27-Jan', Cases: 1 },
            { notification_date: '28-Jan', Cases: 0 },
            { notification_date: '29-Jan', Cases: 0 },
            { notification_date: '30-Jan', Cases: 0 },
            { notification_date: '31-Jan', Cases: 0 },
            { notification_date: '01-Feb', Cases: 0 },
            { notification_date: '02-Feb', Cases: 0 },
            { notification_date: '03-Feb', Cases: 0 },
            { notification_date: '04-Feb', Cases: 0 },
            { notification_date: '05-Feb', Cases: 0 },
            { notification_date: '06-Feb', Cases: 0 },
            { notification_date: '07-Feb', Cases: 0 },
            { notification_date: '08-Feb', Cases: 0 },
            { notification_date: '09-Feb', Cases: 0 },
            { notification_date: '10-Feb', Cases: 0 },
            { notification_date: '11-Feb', Cases: 0 },
            { notification_date: '12-Feb', Cases: 0 },
            { notification_date: '13-Feb', Cases: 0 },
            { notification_date: '14-Feb', Cases: 0 },
            { notification_date: '15-Feb', Cases: 0 },
            { notification_date: '16-Feb', Cases: 0 },
            { notification_date: '17-Feb', Cases: 0 },
            { notification_date: '18-Feb', Cases: 0 },
            { notification_date: '19-Feb', Cases: 0 },
            { notification_date: '20-Feb', Cases: 0 },
            { notification_date: '21-Feb', Cases: 0 },
            { notification_date: '22-Feb', Cases: 0 },
            { notification_date: '23-Feb', Cases: 0 },
            { notification_date: '24-Feb', Cases: 0 },
            { notification_date: '25-Feb', Cases: 0 },
            { notification_date: '26-Feb', Cases: 0 },
            { notification_date: '27-Feb', Cases: 0 },
            { notification_date: '28-Feb', Cases: 0 },
            { notification_date: '29-Feb', Cases: 0 },
            { notification_date: '01-Mar', Cases: 2 },
            { notification_date: '02-Mar', Cases: 3 },
            { notification_date: '03-Mar', Cases: 6 },
            { notification_date: '04-Mar', Cases: 6 },
            { notification_date: '05-Mar', Cases: 4 },
            { notification_date: '06-Mar', Cases: 7 },
            { notification_date: '07-Mar', Cases: 2 },
            { notification_date: '08-Mar', Cases: 7 },
            { notification_date: '09-Mar', Cases: 13 },
            { notification_date: '10-Mar', Cases: 6 },
            { notification_date: '11-Mar', Cases: 16 },
            { notification_date: '12-Mar', Cases: 14 },
            { notification_date: '13-Mar', Cases: 19 },
            { notification_date: '14-Mar', Cases: 20 },
            { notification_date: '15-Mar', Cases: 38 },
            { notification_date: '16-Mar', Cases: 29 },
            { notification_date: '17-Mar', Cases: 64 },
            { notification_date: '18-Mar', Cases: 45 },
            { notification_date: '19-Mar', Cases: 56 },
            { notification_date: '20-Mar', Cases: 88 },
            { notification_date: '21-Mar', Cases: 122 },
            { notification_date: '22-Mar', Cases: 121 },
            { notification_date: '23-Mar', Cases: 177 },
            { notification_date: '24-Mar', Cases: 192 },
            { notification_date: '25-Mar', Cases: 206 },
            { notification_date: '26-Mar', Cases: 185 },
            { notification_date: '27-Mar', Cases: 213 },
            { notification_date: '28-Mar', Cases: 143 },
            { notification_date: '29-Mar', Cases: 124 },
            { notification_date: '30-Mar', Cases: 90 },
            { notification_date: '31-Mar', Cases: 131 },
            { notification_date: '01-Apr', Cases: 124 },
            { notification_date: '02-Apr', Cases: 92 },
            { notification_date: '03-Apr', Cases: 106 },
            { notification_date: '04-Apr', Cases: 73 },
            { notification_date: '05-Apr', Cases: 63 },
            { notification_date: '06-Apr', Cases: 40 },
            { notification_date: '07-Apr', Cases: 44 },
            { notification_date: '08-Apr', Cases: 44 },
            { notification_date: '09-Apr', Cases: 41 },
            { notification_date: '10-Apr', Cases: 30 },
            { notification_date: '11-Apr', Cases: 18 },
            { notification_date: '12-Apr', Cases: 9 },
            { notification_date: '13-Apr', Cases: 7 },
            { notification_date: '14-Apr', Cases: 21 },
            { notification_date: '15-Apr', Cases: 22 },
            { notification_date: '16-Apr', Cases: 22 },
            { notification_date: '17-Apr', Cases: 15 },
            { notification_date: '18-Apr', Cases: 17 },
            { notification_date: '19-Apr', Cases: 7 },
            { notification_date: '20-Apr', Cases: 2 },
            { notification_date: '21-Apr', Cases: 6 },
            { notification_date: '22-Apr', Cases: 3 },
            { notification_date: '23-Apr', Cases: 8 },
            { notification_date: '24-Apr', Cases: 14 },
            { notification_date: '25-Apr', Cases: 3 },
            { notification_date: '26-Apr', Cases: 1 },
            { notification_date: '27-Apr', Cases: 5 },
            { notification_date: '28-Apr', Cases: 10 },
            { notification_date: '29-Apr', Cases: 3 },
            { notification_date: '30-Apr', Cases: 15 },
            { notification_date: '01-May', Cases: 2 },
            { notification_date: '02-May', Cases: 2 },
            { notification_date: '03-May', Cases: 1 },
            { notification_date: '04-May', Cases: 4 },
            { notification_date: '05-May', Cases: 5 },
            { notification_date: '06-May', Cases: 3 },
            { notification_date: '07-May', Cases: 2 },
            { notification_date: '08-May', Cases: 4 },
            { notification_date: '09-May', Cases: 1 },
            { notification_date: '10-May', Cases: 1 },
            { notification_date: '11-May', Cases: 0 },
            { notification_date: '12-May', Cases: 5 },
            { notification_date: '13-May', Cases: 4 },
            { notification_date: '14-May', Cases: 3 },
            { notification_date: '15-May', Cases: 2 },
            { notification_date: '16-May', Cases: 0 },
            { notification_date: '17-May', Cases: 1 },
            { notification_date: '18-May', Cases: 2 },
            { notification_date: '19-May', Cases: 4 },
            { notification_date: '20-May', Cases: 1 },
            { notification_date: '21-May', Cases: 3 },
            { notification_date: '22-May', Cases: 0 },
            { notification_date: '23-May', Cases: 1 },
            { notification_date: '24-May', Cases: 1 },
            { notification_date: '25-May', Cases: 2 },
            { notification_date: '26-May', Cases: 0 },
            { notification_date: '27-May', Cases: 1 },
            { notification_date: '28-May', Cases: 2 },
            { notification_date: '29-May', Cases: 1 },
            { notification_date: '30-May', Cases: 2 },
            { notification_date: '31-May', Cases: 5 },
            { notification_date: '01-Jun', Cases: 4 },
            { notification_date: '02-Jun', Cases: 1 },
            { notification_date: '03-Jun', Cases: 2 },
            { notification_date: '04-Jun', Cases: 3 },
            { notification_date: '05-Jun', Cases: 0 },
            { notification_date: '06-Jun', Cases: 1 },
            { notification_date: '07-Jun', Cases: 3 },
            { notification_date: '08-Jun', Cases: 1 },
            { notification_date: '09-Jun', Cases: 3 },
            { notification_date: '10-Jun', Cases: 0 },
            { notification_date: '11-Jun', Cases: 3 },
            { notification_date: '12-Jun', Cases: 3 },
            { notification_date: '13-Jun', Cases: 9 },
            { notification_date: '14-Jun', Cases: 6 },
            { notification_date: '15-Jun', Cases: 0 },
            { notification_date: '16-Jun', Cases: 0 },
            { notification_date: '17-Jun', Cases: 2 },
            { notification_date: '18-Jun', Cases: 7 },
            { notification_date: '19-Jun', Cases: 1 },
            { notification_date: '20-Jun', Cases: 6 },
            { notification_date: '21-Jun', Cases: 1 },
            { notification_date: '22-Jun', Cases: 1 },
            { notification_date: '23-Jun', Cases: 10 },
            { notification_date: '24-Jun', Cases: 4 },
            { notification_date: '25-Jun', Cases: 6 },
            { notification_date: '26-Jun', Cases: 5 },
            { notification_date: '27-Jun', Cases: 10 },
            { notification_date: '28-Jun', Cases: 3 },
            { notification_date: '29-Jun', Cases: 6 },
            { notification_date: '30-Jun', Cases: 11 },
            { notification_date: '01-Jul', Cases: 6 },
            { notification_date: '02-Jul', Cases: 5 },
            { notification_date: '03-Jul', Cases: 8 },
            { notification_date: '04-Jul', Cases: 12 },
            { notification_date: '05-Jul', Cases: 8 },
            { notification_date: '06-Jul', Cases: 13 },
            { notification_date: '07-Jul', Cases: 6 },
            { notification_date: '08-Jul', Cases: 13 },
            { notification_date: '09-Jul', Cases: 9 },
            { notification_date: '10-Jul', Cases: 8 },
            { notification_date: '11-Jul', Cases: 2 },
            { notification_date: '12-Jul', Cases: 15 },
            { notification_date: '13-Jul', Cases: 17 },
            { notification_date: '14-Jul', Cases: 10 },
            { notification_date: '15-Jul', Cases: 9 },
            { notification_date: '16-Jul', Cases: 9 },
            { notification_date: '17-Jul', Cases: 13 },
            { notification_date: '18-Jul', Cases: 17 },
            { notification_date: '19-Jul', Cases: 20 },
            { notification_date: '20-Jul', Cases: 14 },
            { notification_date: '21-Jul', Cases: 14 },
            { notification_date: '22-Jul', Cases: 16 },
            { notification_date: '23-Jul', Cases: 7 },
            { notification_date: '24-Jul', Cases: 18 },
            { notification_date: '25-Jul', Cases: 18 },
            { notification_date: '26-Jul', Cases: 9 },
            { notification_date: '27-Jul', Cases: 15 },
            { notification_date: '28-Jul', Cases: 22 },
            { notification_date: '29-Jul', Cases: 15 },
            { notification_date: '30-Jul', Cases: 22 },
            { notification_date: '31-Jul', Cases: 15 },
            { notification_date: '01-Aug', Cases: 14 },
            { notification_date: '02-Aug', Cases: 11 },
            { notification_date: '03-Aug', Cases: 13 },
            { notification_date: '04-Aug', Cases: 9 },
            { notification_date: '05-Aug', Cases: 13 },
            { notification_date: '06-Aug', Cases: 11 },
            { notification_date: '07-Aug', Cases: 8 },
            { notification_date: '08-Aug', Cases: 14 },
            { notification_date: '09-Aug', Cases: 13 },
            { notification_date: '10-Aug', Cases: 22 },
            { notification_date: '11-Aug', Cases: 15 },
            { notification_date: '12-Aug', Cases: 10 },
            { notification_date: '13-Aug', Cases: 14 },
            { notification_date: '14-Aug', Cases: 7 },
            { notification_date: '15-Aug', Cases: 6 },
            { notification_date: '16-Aug', Cases: 5 },
            { notification_date: '17-Aug', Cases: 3 },
            { notification_date: '18-Aug', Cases: 8 },
            { notification_date: '19-Aug', Cases: 2 },
            { notification_date: '20-Aug', Cases: 5 },
            { notification_date: '21-Aug', Cases: 7 },
            { notification_date: '22-Aug', Cases: 2 },
            { notification_date: '23-Aug', Cases: 3 },
            { notification_date: '24-Aug', Cases: 4 },
            { notification_date: '25-Aug', Cases: 6 },
            { notification_date: '26-Aug', Cases: 12 },
            { notification_date: '27-Aug', Cases: 15 },
            { notification_date: '28-Aug', Cases: 10 },
            { notification_date: '29-Aug', Cases: 7 },
            { notification_date: '30-Aug', Cases: 11 },
            { notification_date: '31-Aug', Cases: 12 },
            { notification_date: '01-Sep', Cases: 15 },
            { notification_date: '02-Sep', Cases: 10 },
            { notification_date: '03-Sep', Cases: 7 },
            { notification_date: '04-Sep', Cases: 7 },
            { notification_date: '05-Sep', Cases: 8 },
            { notification_date: '06-Sep', Cases: 4 },
            { notification_date: '07-Sep', Cases: 11 },
            { notification_date: '08-Sep', Cases: 5 },
            { notification_date: '09-Sep', Cases: 10 },
            { notification_date: '10-Sep', Cases: 8 },
            { notification_date: '11-Sep', Cases: 8 },
            { notification_date: '12-Sep', Cases: 6 },
            { notification_date: '13-Sep', Cases: 7 },
            { notification_date: '14-Sep', Cases: 7 },
            { notification_date: '15-Sep', Cases: 5 },
            { notification_date: '16-Sep', Cases: 7 },
            { notification_date: '17-Sep', Cases: 3 },
            { notification_date: '18-Sep', Cases: 4 },
            { notification_date: '19-Sep', Cases: 1 },
            { notification_date: '20-Sep', Cases: 5 },
            { notification_date: '21-Sep', Cases: 1 },
            { notification_date: '22-Sep', Cases: 6 },
            { notification_date: '23-Sep', Cases: 3 },
            { notification_date: '24-Sep', Cases: 2 },
            { notification_date: '25-Sep', Cases: 1 },
            { notification_date: '26-Sep', Cases: 0 },
            { notification_date: '27-Sep', Cases: 0 },
            { notification_date: '28-Sep', Cases: 5 },
            { notification_date: '29-Sep', Cases: 2 },
            { notification_date: '30-Sep', Cases: 4 },
            { notification_date: '01-Oct', Cases: 3 },
            { notification_date: '02-Oct', Cases: 0 },
            { notification_date: '03-Oct', Cases: 3 },
            { notification_date: '04-Oct', Cases: 2 },
            { notification_date: '05-Oct', Cases: 9 },
            { notification_date: '06-Oct', Cases: 3 },
            { notification_date: '07-Oct', Cases: 15 },
            { notification_date: '08-Oct', Cases: 6 },
            { notification_date: '09-Oct', Cases: 4 },
            { notification_date: '10-Oct', Cases: 7 },
            { notification_date: '11-Oct', Cases: 5 },
            { notification_date: '12-Oct', Cases: 15 },
            { notification_date: '13-Oct', Cases: 12 },
            { notification_date: '14-Oct', Cases: 10 },
            { notification_date: '15-Oct', Cases: 3 },
            { notification_date: '16-Oct', Cases: 7 },
            { notification_date: '17-Oct', Cases: 6 },
            { notification_date: '18-Oct', Cases: 6 },
            { notification_date: '19-Oct', Cases: 10 },
            { notification_date: '20-Oct', Cases: 4 },
            { notification_date: '21-Oct', Cases: 9 },
            { notification_date: '22-Oct', Cases: 3 },
            { notification_date: '23-Oct', Cases: 6 },
            { notification_date: '24-Oct', Cases: 7 },
            { notification_date: '25-Oct', Cases: 3 },
            { notification_date: '26-Oct', Cases: 15 },
            { notification_date: '27-Oct', Cases: 5 },
            { notification_date: '28-Oct', Cases: 4 },
            { notification_date: '29-Oct', Cases: 7 },
            { notification_date: '30-Oct', Cases: 4 },
            { notification_date: '31-Oct', Cases: 5 },
            { notification_date: '01-Nov', Cases: 5 },
            { notification_date: '02-Nov', Cases: 4 },
            { notification_date: '03-Nov', Cases: 7 },
            { notification_date: '04-Nov', Cases: 3 },
            { notification_date: '05-Nov', Cases: 10 },
            { notification_date: '06-Nov', Cases: 5 },
            { notification_date: '07-Nov', Cases: 4 },
            { notification_date: '08-Nov', Cases: 7 },
            { notification_date: '09-Nov', Cases: 5 },
            { notification_date: '10-Nov', Cases: 2 },
            { notification_date: '11-Nov', Cases: 5 },
            { notification_date: '12-Nov', Cases: 2 },
            { notification_date: '13-Nov', Cases: 6 },
            { notification_date: '14-Nov', Cases: 8 },
            { notification_date: '15-Nov', Cases: 2 },
            { notification_date: '16-Nov', Cases: 4 },
            { notification_date: '17-Nov', Cases: 6 },
            { notification_date: '18-Nov', Cases: 7 },
            { notification_date: '19-Nov', Cases: 3 },
            { notification_date: '20-Nov', Cases: 10 },
            { notification_date: '21-Nov', Cases: 9 },
            { notification_date: '22-Nov', Cases: 5 },
            { notification_date: '23-Nov', Cases: 7 },
            { notification_date: '24-Nov', Cases: 2 },
            { notification_date: '25-Nov', Cases: 0 },
            { notification_date: '26-Nov', Cases: 5 },
            { notification_date: '27-Nov', Cases: 8 },
            { notification_date: '28-Nov', Cases: 4 },
            { notification_date: '29-Nov', Cases: 7 },
            { notification_date: '30-Nov', Cases: 8 },
            { notification_date: '01-Dec', Cases: 6 },
            { notification_date: '02-Dec', Cases: 8 },
            { notification_date: '03-Dec', Cases: 4 },
            { notification_date: '04-Dec', Cases: 2 },
            { notification_date: '05-Dec', Cases: 5 },
            { notification_date: '06-Dec', Cases: 7 },
            { notification_date: '07-Dec', Cases: 4 },
            { notification_date: '08-Dec', Cases: 2 },
            { notification_date: '09-Dec', Cases: 9 },
            { notification_date: '10-Dec', Cases: 6 },
            { notification_date: '11-Dec', Cases: 3 },
            { notification_date: '12-Dec', Cases: 3 },
            { notification_date: '13-Dec', Cases: 5 },
            { notification_date: '14-Dec', Cases: 7 },
            { notification_date: '15-Dec', Cases: 3 },
            { notification_date: '16-Dec', Cases: 9 },
            { notification_date: '17-Dec', Cases: 25 },
            { notification_date: '18-Dec', Cases: 28 },
            { notification_date: '19-Dec', Cases: 32 },
            { notification_date: '20-Dec', Cases: 28 },
            { notification_date: '21-Dec', Cases: 12 },
            { notification_date: '22-Dec', Cases: 13 },
            { notification_date: '23-Dec', Cases: 21 },
            { notification_date: '24-Dec', Cases: 12 },
            { notification_date: '25-Dec', Cases: 11 },
            { notification_date: '26-Dec', Cases: 13 },
            { notification_date: '27-Dec', Cases: 10 },
            { notification_date: '28-Dec', Cases: 9 },
            { notification_date: '29-Dec', Cases: 30 },
            { notification_date: '30-Dec', Cases: 9 },
            { notification_date: '31-Dec', Cases: 11 },
            { notification_date: '01-Jan', Cases: 17 },
            { notification_date: '02-Jan', Cases: 7 },
            { notification_date: '03-Jan', Cases: 11 },
            { notification_date: '04-Jan', Cases: 4 },
            { notification_date: '05-Jan', Cases: 4 },
            { notification_date: '06-Jan', Cases: 12 },
            { notification_date: '07-Jan', Cases: 5 },
            { notification_date: '08-Jan', Cases: 11 },
            { notification_date: '09-Jan', Cases: 7 },
            { notification_date: '10-Jan', Cases: 12 },
            { notification_date: '11-Jan', Cases: 11 },
            { notification_date: '12-Jan', Cases: 5 },
            { notification_date: '13-Jan', Cases: 2 },
            { notification_date: '14-Jan', Cases: 2 },
            { notification_date: '15-Jan', Cases: 14 },
            { notification_date: '16-Jan', Cases: 14 },
            { notification_date: '17-Jan', Cases: 2 },
            { notification_date: '18-Jan', Cases: 1 },
            { notification_date: '19-Jan', Cases: 4 },
            { notification_date: '20-Jan', Cases: 5 },
            { notification_date: '21-Jan', Cases: 0 },
            { notification_date: '22-Jan', Cases: 1 },
            { notification_date: '23-Jan', Cases: 5 },
            { notification_date: '24-Jan', Cases: 1 },
            { notification_date: '25-Jan', Cases: 3 },
            { notification_date: '26-Jan', Cases: 1 },
            { notification_date: '27-Jan', Cases: 4 },
            { notification_date: '28-Jan', Cases: 4 },
            { notification_date: '29-Jan', Cases: 3 },
            { notification_date: '30-Jan', Cases: 2 },
            { notification_date: '31-Jan', Cases: 4 },
            { notification_date: '01-Feb', Cases: 2 },
            { notification_date: '02-Feb', Cases: 2 },
            { notification_date: '03-Feb', Cases: 3 },
            { notification_date: '04-Feb', Cases: 0 },
            { notification_date: '05-Feb', Cases: 4 },
            { notification_date: '06-Feb', Cases: 0 },
            { notification_date: '07-Feb', Cases: 5 },
            { notification_date: '08-Feb', Cases: 4 },
            { notification_date: '09-Feb', Cases: 1 },
            { notification_date: '10-Feb', Cases: 2 },
            { notification_date: '11-Feb', Cases: 2 },
            { notification_date: '12-Feb', Cases: 2 },
            { notification_date: '13-Feb', Cases: 2 },
            { notification_date: '14-Feb', Cases: 0 },
            { notification_date: '15-Feb', Cases: 2 },
            { notification_date: '16-Feb', Cases: 3 },
            { notification_date: '17-Feb', Cases: 1 },
            { notification_date: '18-Feb', Cases: 2 },
            { notification_date: '19-Feb', Cases: 1 },
            { notification_date: '20-Feb', Cases: 3 },
            { notification_date: '21-Feb', Cases: 1 },
            { notification_date: '22-Feb', Cases: 4 },
            { notification_date: '23-Feb', Cases: 4 },
            { notification_date: '24-Feb', Cases: 5 },
            { notification_date: '25-Feb', Cases: 4 },
            { notification_date: '26-Feb', Cases: 4 },
            { notification_date: '27-Feb', Cases: 4 },
            { notification_date: '28-Feb', Cases: 6 },
            { notification_date: '01-Mar', Cases: 1 },
            { notification_date: '02-Mar', Cases: 5 },
            { notification_date: '03-Mar', Cases: 6 },
            { notification_date: '04-Mar', Cases: 9 },
            { notification_date: '05-Mar', Cases: 4 },
            { notification_date: '06-Mar', Cases: 1 },
            { notification_date: '07-Mar', Cases: 1 },
            { notification_date: '08-Mar', Cases: 5 },
            { notification_date: '09-Mar', Cases: 6 },
            { notification_date: '10-Mar', Cases: 7 },
            { notification_date: '11-Mar', Cases: 6 },
            { notification_date: '12-Mar', Cases: 0 },
            { notification_date: '13-Mar', Cases: 5 },
            { notification_date: '14-Mar', Cases: 3 },
            { notification_date: '15-Mar', Cases: 1 },
            { notification_date: '16-Mar', Cases: 6 },
            { notification_date: '17-Mar', Cases: 8 },
            { notification_date: '18-Mar', Cases: 1 },
            { notification_date: '19-Mar', Cases: 2 },
            { notification_date: '20-Mar', Cases: 5 },
            { notification_date: '21-Mar', Cases: 4 },
            { notification_date: '22-Mar', Cases: 2 },
            { notification_date: '23-Mar', Cases: 4 },
            { notification_date: '24-Mar', Cases: 3 },
            { notification_date: '25-Mar', Cases: 2 },
            { notification_date: '26-Mar', Cases: 3 },
            { notification_date: '27-Mar', Cases: 0 },
            { notification_date: '28-Mar', Cases: 4 },
            { notification_date: '29-Mar', Cases: 4 },
            { notification_date: '30-Mar', Cases: 5 },
            { notification_date: '31-Mar', Cases: 2 },
            { notification_date: '01-Apr', Cases: 0 },
            { notification_date: '02-Apr', Cases: 3 },
            { notification_date: '03-Apr', Cases: 1 },
            { notification_date: '04-Apr', Cases: 4 },
            { notification_date: '05-Apr', Cases: 9 },
            { notification_date: '06-Apr', Cases: 5 },
            { notification_date: '07-Apr', Cases: 1 },
            { notification_date: '08-Apr', Cases: 3 },
            { notification_date: '09-Apr', Cases: 5 },
            { notification_date: '10-Apr', Cases: 7 },
            { notification_date: '11-Apr', Cases: 6 },
            { notification_date: '12-Apr', Cases: 4 },
            { notification_date: '13-Apr', Cases: 4 },
            { notification_date: '14-Apr', Cases: 12 },
            { notification_date: '15-Apr', Cases: 1 },
            { notification_date: '16-Apr', Cases: 9 },
            { notification_date: '17-Apr', Cases: 4 },
            { notification_date: '18-Apr', Cases: 9 },
            { notification_date: '19-Apr', Cases: 4 },
            { notification_date: '20-Apr', Cases: 7 },
            { notification_date: '21-Apr', Cases: 15 },
            { notification_date: '22-Apr', Cases: 5 },
            { notification_date: '23-Apr', Cases: 1 },
            { notification_date: '24-Apr', Cases: 4 },
            { notification_date: '25-Apr', Cases: 7 },
            { notification_date: '26-Apr', Cases: 16 },
            { notification_date: '27-Apr', Cases: 12 },
            { notification_date: '28-Apr', Cases: 17 },
            { notification_date: '29-Apr', Cases: 2 },
            { notification_date: '30-Apr', Cases: 4 },
            { notification_date: '01-May', Cases: 2 },
            { notification_date: '02-May', Cases: 8 },
            { notification_date: '03-May', Cases: 9 },
            { notification_date: '04-May', Cases: 7 },
            { notification_date: '05-May', Cases: 9 },
            { notification_date: '06-May', Cases: 4 },
            { notification_date: '07-May', Cases: 5 },
            { notification_date: '08-May', Cases: 7 },
            { notification_date: '09-May', Cases: 6 },
            { notification_date: '10-May', Cases: 4 },
            { notification_date: '11-May', Cases: 2 },
            { notification_date: '12-May', Cases: 5 },
            { notification_date: '13-May', Cases: 3 },
            { notification_date: '14-May', Cases: 2 },
            { notification_date: '15-May', Cases: 2 },
            { notification_date: '16-May', Cases: 2 },
            { notification_date: '17-May', Cases: 3 },
            { notification_date: '18-May', Cases: 2 },
            { notification_date: '19-May', Cases: 2 },
            { notification_date: '20-May', Cases: 0 },
            { notification_date: '21-May', Cases: 3 },
            { notification_date: '22-May', Cases: 0 },
            { notification_date: '23-May', Cases: 2 },
            { notification_date: '24-May', Cases: 2 },
            { notification_date: '25-May', Cases: 2 },
            { notification_date: '26-May', Cases: 0 },
            { notification_date: '27-May', Cases: 4 },
            { notification_date: '28-May', Cases: 2 },
            { notification_date: '29-May', Cases: 3 },
            { notification_date: '30-May', Cases: 2 },
            { notification_date: '31-May', Cases: 0 },
            { notification_date: '01-Jun', Cases: 1 },
            { notification_date: '02-Jun', Cases: 2 },
            { notification_date: '03-Jun', Cases: 0 },
            { notification_date: '04-Jun', Cases: 4 },
            { notification_date: '05-Jun', Cases: 3 },
            { notification_date: '06-Jun', Cases: 4 },
            { notification_date: '07-Jun', Cases: 8 },
            { notification_date: '08-Jun', Cases: 1 },
            { notification_date: '09-Jun', Cases: 2 },
            { notification_date: '10-Jun', Cases: 2 },
            { notification_date: '11-Jun', Cases: 0 },
            { notification_date: '12-Jun', Cases: 1 },
            { notification_date: '13-Jun', Cases: 8 },
            { notification_date: '14-Jun', Cases: 4 },
            { notification_date: '15-Jun', Cases: 1 },
            { notification_date: '16-Jun', Cases: 4 },
            { notification_date: '17-Jun', Cases: 1 },
            { notification_date: '18-Jun', Cases: 7 },
            { notification_date: '19-Jun', Cases: 7 },
            { notification_date: '20-Jun', Cases: 3 },
            { notification_date: '21-Jun', Cases: 5 },
            { notification_date: '22-Jun', Cases: 19 },
            { notification_date: '23-Jun', Cases: 12 },
            { notification_date: '24-Jun', Cases: 22 },
            { notification_date: '25-Jun', Cases: 28 },
            { notification_date: '26-Jun', Cases: 28 },
            { notification_date: '27-Jun', Cases: 23 },
            { notification_date: '28-Jun', Cases: 16 },
            { notification_date: '29-Jun', Cases: 31 },
            { notification_date: '30-Jun', Cases: 31 },
            { notification_date: '01-Jul', Cases: 31 },
            { notification_date: '02-Jul', Cases: 42 },
            { notification_date: '03-Jul', Cases: 24 },
            { notification_date: '04-Jul', Cases: 31 },
            { notification_date: '05-Jul', Cases: 17 },
            { notification_date: '06-Jul', Cases: 34 },
            { notification_date: '07-Jul', Cases: 37 },
            { notification_date: '08-Jul', Cases: 46 },
            { notification_date: '09-Jul', Cases: 52 },
            { notification_date: '10-Jul', Cases: 107 },
            { notification_date: '11-Jul', Cases: 121 },
            { notification_date: '12-Jul', Cases: 73 },
            { notification_date: '13-Jul', Cases: 91 },
            { notification_date: '14-Jul', Cases: 76 },
            { notification_date: '15-Jul', Cases: 102 },
            { notification_date: '16-Jul', Cases: 114 },
            { notification_date: '17-Jul', Cases: 99 },
            { notification_date: '18-Jul', Cases: 111 },
            { notification_date: '19-Jul', Cases: 66 },
            { notification_date: '20-Jul', Cases: 107 },
            { notification_date: '21-Jul', Cases: 143 },
            { notification_date: '22-Jul', Cases: 144 },
            { notification_date: '23-Jul', Cases: 150 },
            { notification_date: '24-Jul', Cases: 141 },
            { notification_date: '25-Jul', Cases: 176 },
            { notification_date: '26-Jul', Cases: 143 },
            { notification_date: '27-Jul', Cases: 158 },
            { notification_date: '28-Jul', Cases: 255 },
            { notification_date: '29-Jul', Cases: 182 },
            { notification_date: '30-Jul', Cases: 197 },
            { notification_date: '31-Jul', Cases: 242 },
            { notification_date: '01-Aug', Cases: 194 },
            { notification_date: '02-Aug', Cases: 208 },
            { notification_date: '03-Aug', Cases: 237 },
            { notification_date: '04-Aug', Cases: 247 },
            { notification_date: '05-Aug', Cases: 320 },
            { notification_date: '06-Aug', Cases: 302 },
            { notification_date: '07-Aug', Cases: 252 },
            { notification_date: '08-Aug', Cases: 260 },
            { notification_date: '09-Aug', Cases: 367 },
            { notification_date: '10-Aug', Cases: 339 },
            { notification_date: '11-Aug', Cases: 372 },
            { notification_date: '12-Aug', Cases: 401 },
            { notification_date: '13-Aug', Cases: 454 },
            { notification_date: '14-Aug', Cases: 325 },
            { notification_date: '15-Aug', Cases: 508 },
            { notification_date: '16-Aug', Cases: 580 },
            { notification_date: '17-Aug', Cases: 550 },
            { notification_date: '18-Aug', Cases: 638 },
            { notification_date: '19-Aug', Cases: 764 },
            { notification_date: '20-Aug', Cases: 771 },
            { notification_date: '21-Aug', Cases: 817 },
            { notification_date: '22-Aug', Cases: 745 },
            { notification_date: '23-Aug', Cases: 831 },
            { notification_date: '24-Aug', Cases: 918 },
            { notification_date: '25-Aug', Cases: 967 },
            { notification_date: '26-Aug', Cases: 948 },
            { notification_date: '27-Aug', Cases: 1138 },
            { notification_date: '28-Aug', Cases: 1140 },
            { notification_date: '29-Aug', Cases: 1224 },
            { notification_date: '30-Aug', Cases: 1099 },
            { notification_date: '31-Aug', Cases: 1248 },
            { notification_date: '01-Sep', Cases: 1373 },
            { notification_date: '02-Sep', Cases: 1417 },
            { notification_date: '03-Sep', Cases: 1200 },
          ],
        };
        this.getLocationsData(this.locationsData);
      }
    );
  }
  getLocationsData(locationsData) {
    locationsData.data.forEach((element) => {
      let finalData = [];
      finalData.push(element?.notification_date, element?.Cases);
      this.data.push(finalData);
    });
    this.getChartOptions();
  }

  getChartOptions() {
    this.chartOptions = {
      xAxis: {
        type: 'category',
        labels: {
          rotation: -45,
          style: {
            fontSize: '13px',
            fontFamily: 'Verdana, sans-serif',
          },
        },
      },
      yAxis: {
        min: 0,
        title: {
          text: 'Cases',
        },
      },
      legend: {
        enabled: false,
      },
      title: {
        text: null,
      },
      tooltip: {
        pointFormat: 'Cases: <b>{point.x}</b>',
        style: {
          fontSize: '13px',
          fontFamily: 'Verdana, sans-serif',
        },
      },
      series: [
        {
          type: 'column',
          data: this.data,
        },
      ],
    };
  }

  getStats(): void {
    this.caremonitorService.getStatistics().subscribe(
      (res: Istatistics) => {
        this.totalData = res;
        this.newCases = this.totalData?.data[0]?.LocalCases_24hrs;
        this.InterStateCases = this.totalData?.data[0]?.InterStateCases_24hrs;
        this.hospitalCases =
          this.totalData?.data[0]?.concurrentHospitalisations;
        this.icuCases = this.totalData?.data[0]?.concurrentHospitalisationsIcu;
        this.ventilatorCases =
          this.totalData?.data[0]?.concurrentHospitalisationsVentilated;
        this.Test_24hrs = this.totalData?.data[0]?.Test_24hrs;
        this.NewCases = this.totalData?.data[0]?.NewCases;
        this.Tested = this.totalData?.data[0]?.Tested;
        this.LocalCases = this.totalData?.data[0]?.LocalCases;
        this.Deaths = this.totalData?.data[0]?.Deaths;
        this.Cases = this.totalData?.data[0]?.Cases;
      },
      (err) => {
        this.totalData = {
          data: [
            {
              Recovered: 3167,
              LocalCasesWithKnownSource: 12452,
              OverseasCases: 3427,
              LocalCases: 28611,
              Tested: 13781014,
              CaseStatsReportingDateUnixTimestamp: 1630663200000,
              concurrentHospitalisationsIcu: 173,
              Test_24hrs: 131174,
              LocalCases_24hrs: 1533,
              CaseStatsReportingDate: '2021-09-03',
              InterStateCases: 96,
              TestStatsReportingDateUnixTimestamp: 1630663200000,
              Deaths: 179,
              InterStateCases_24hrs: 0,
              concurrentHospitalisationsVentilated: 96,
              OverseasCases_24hrs: 1,
              concurrentHospitalisations: 1036,
              LocalCasesWithKnownSource_24hrs: 175,
              TestStatsReportingDate: '2021-09-03',
              hospitalisationsReportingDateUnixTimestamp: 1630659600000,
              LocalCasesWithUnknownSource: 15565,
              hospitalisationsReportingDate: '2021-09-03',
              NewCases: 1534,
              LocalCasesWithUnknownSource_24hrs: 1358,
              Cases: 32134,
            },
          ],
        };
        this.newCases = this.totalData?.data[0]?.LocalCases_24hrs;
        this.InterStateCases = this.totalData?.data[0]?.InterStateCases_24hrs;
        this.hospitalCases =
          this.totalData?.data[0]?.concurrentHospitalisations;
        this.icuCases = this.totalData?.data[0]?.concurrentHospitalisationsIcu;
        this.ventilatorCases =
          this.totalData?.data[0]?.concurrentHospitalisationsVentilated;
        this.Test_24hrs = this.totalData?.data[0]?.Test_24hrs;
        this.NewCases = this.totalData?.data[0]?.NewCases;
        this.Tested = this.totalData?.data[0]?.Tested;
        this.LocalCases = this.totalData?.data[0]?.LocalCases;
        this.Deaths = this.totalData?.data[0]?.Deaths;
        this.Cases = this.totalData?.data[0]?.Cases;
      }
    );
  }

  totalVaccinationsStats: any;
  getVaccinationStats(): void {
    this.caremonitorService.getVaccinationStats().subscribe(
      (res: IStateVaccinationMetrics) => {
        this.totalVaccinationsStats = res;
        this.getVaccineStats(this.totalVaccinationsStats);
      },
      (err) => {
        this.totalVaccinationsStats = {
          nswHealthDosesDaily: 49779,
          nswHealthDosesCumulative: 2750897,
          gpNetworkDosesCumulative: 4601473,
          allProvidersDosesCumulative: 7352370,
          nswHealthUpdatedDate: '2021-09-03',
          gpNetworkUpdatedDate: '2021-09-02',
          nswHealthDosesLast3Days: 139692,
          daysAvailableInLast3: 3,
        };
        this.getVaccineStats(this.totalVaccinationsStats);
      }
    );
  }

  getVaccineStats(totalVaccinationsStats) {
    this.nswHealthDosesDaily = totalVaccinationsStats['nswHealthDosesDaily'];
    this.nswHealthDosesCumulative =
      totalVaccinationsStats['nswHealthDosesCumulative'];
    this.gpNetworkDosesCumulative =
      totalVaccinationsStats['gpNetworkDosesCumulative'];
    this.allProvidersDosesCumulative =
      totalVaccinationsStats['allProvidersDosesCumulative'];
  }

  scrollto(dest: string) {
    const el: HTMLElement | null = document.getElementById(dest);
    if (el) {
      interval(0)
        .pipe(take(1))
        .subscribe(() =>
          el.scrollIntoView({
            behavior: 'smooth',
            block: 'center',
            inline: 'nearest',
          })
        );
    }
  }
}
